In [1]:
from game_utils import *
from keras.models     import Sequential
from keras.layers     import Dense, Conv2D, BatchNormalization
from keras.optimizers import Adam, SGD

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
model = Sequential()
model.add(Dense(200, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))
model.add(Dense(200, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))

model.add(Dense(15**2, activation='linear'))

opt = SGD(lr=0.001 , momentum=0.9, decay=1e-18, nesterov=False)

parameterList = {}
parameterList['model'] = model
parameterList['opt'] = opt

fir = FIR(CROSS, False, parameterList, 3000)

In [3]:
fir.run()

Epoch:  100 / 3000 	Elapsed time:  0:01:33
Epoch:  200 / 3000 	Elapsed time:  0:03:09
Epoch:  300 / 3000 	Elapsed time:  0:04:46
Epoch:  400 / 3000 	Elapsed time:  0:06:26
Epoch:  500 / 3000 	Elapsed time:  0:08:09
Epoch:  600 / 3000 	Elapsed time:  0:09:51
Epoch:  700 / 3000 	Elapsed time:  0:11:32
Epoch:  800 / 3000 	Elapsed time:  0:13:11
Epoch:  900 / 3000 	Elapsed time:  0:14:47
Epoch:  1000 / 3000 	Elapsed time:  0:16:22
Epoch:  1100 / 3000 	Elapsed time:  0:18:12
Epoch:  1200 / 3000 	Elapsed time:  0:19:57
Epoch:  1300 / 3000 	Elapsed time:  0:21:21
Epoch:  1400 / 3000 	Elapsed time:  0:22:41
Epoch:  1500 / 3000 	Elapsed time:  0:24:07
Epoch:  1600 / 3000 	Elapsed time:  0:25:25
Epoch:  1700 / 3000 	Elapsed time:  0:26:58
Epoch:  1800 / 3000 	Elapsed time:  0:28:38
Epoch:  1900 / 3000 	Elapsed time:  0:30:22
Epoch:  2000 / 3000 	Elapsed time:  0:31:54
Epoch:  2100 / 3000 	Elapsed time:  0:33:04
Epoch:  2200 / 3000 	Elapsed time:  0:34:22
Epoch:  2300 / 3000 	Elapsed time:  0:35:

In [4]:
fir.test()

[['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' 'X' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']]
-0.01
------------------------------------------------

In [5]:
model = Sequential()
model.add(Dense(400, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))
model.add(Dense(400, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))

model.add(Dense(15**2, activation='linear'))

opt = SGD(lr=0.001 , momentum=0.9, decay=1e-18, nesterov=False)

parameterList = {}
parameterList['model'] = model
parameterList['opt'] = opt

fir = FIR(CROSS, False, parameterList, 3000)

In [6]:
fir.run()

Epoch:  100 / 3000 	Elapsed time:  0:01:29
Epoch:  200 / 3000 	Elapsed time:  0:03:01
Epoch:  300 / 3000 	Elapsed time:  0:04:34
Epoch:  400 / 3000 	Elapsed time:  0:06:13
Epoch:  500 / 3000 	Elapsed time:  0:07:50
Epoch:  600 / 3000 	Elapsed time:  0:09:35
Epoch:  700 / 3000 	Elapsed time:  0:11:04
Epoch:  800 / 3000 	Elapsed time:  0:12:46
Epoch:  900 / 3000 	Elapsed time:  0:14:24
Epoch:  1000 / 3000 	Elapsed time:  0:15:58
Epoch:  1100 / 3000 	Elapsed time:  0:17:38
Epoch:  1200 / 3000 	Elapsed time:  0:19:07
Epoch:  1300 / 3000 	Elapsed time:  0:20:36
Epoch:  1400 / 3000 	Elapsed time:  0:22:13
Epoch:  1500 / 3000 	Elapsed time:  0:23:34
Epoch:  1600 / 3000 	Elapsed time:  0:24:43
Epoch:  1700 / 3000 	Elapsed time:  0:26:12
Epoch:  1800 / 3000 	Elapsed time:  0:27:35
Epoch:  1900 / 3000 	Elapsed time:  0:28:35
Epoch:  2000 / 3000 	Elapsed time:  0:29:49
Epoch:  2100 / 3000 	Elapsed time:  0:31:32
Epoch:  2200 / 3000 	Elapsed time:  0:32:37
Epoch:  2300 / 3000 	Elapsed time:  0:33:

In [7]:
fir.test()

[['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' 'X' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']]
-0.01
------------------------------------------------

In [8]:
fir = FIR(CROSS, False, None, 3000)

In [9]:
fir.run()

Epoch:  100 / 3000 	Elapsed time:  0:01:35
Epoch:  200 / 3000 	Elapsed time:  0:03:14
Epoch:  300 / 3000 	Elapsed time:  0:04:56
Epoch:  400 / 3000 	Elapsed time:  0:06:42
Epoch:  500 / 3000 	Elapsed time:  0:08:30
Epoch:  600 / 3000 	Elapsed time:  0:10:15
Epoch:  700 / 3000 	Elapsed time:  0:11:58
Epoch:  800 / 3000 	Elapsed time:  0:13:41
Epoch:  900 / 3000 	Elapsed time:  0:15:24
Epoch:  1000 / 3000 	Elapsed time:  0:17:10
Epoch:  1100 / 3000 	Elapsed time:  0:18:48
Epoch:  1200 / 3000 	Elapsed time:  0:20:31
Epoch:  1300 / 3000 	Elapsed time:  0:22:14
Epoch:  1400 / 3000 	Elapsed time:  0:23:50
Epoch:  1500 / 3000 	Elapsed time:  0:25:23
Epoch:  1600 / 3000 	Elapsed time:  0:26:45
Epoch:  1700 / 3000 	Elapsed time:  0:27:55
Epoch:  1800 / 3000 	Elapsed time:  0:28:53
Epoch:  1900 / 3000 	Elapsed time:  0:30:04
Epoch:  2000 / 3000 	Elapsed time:  0:31:29
Epoch:  2100 / 3000 	Elapsed time:  0:32:56
Epoch:  2200 / 3000 	Elapsed time:  0:33:44
Epoch:  2300 / 3000 	Elapsed time:  0:34:

In [10]:
fir.test()

[['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' 'X' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']]
-0.01
------------------------------------------------

In [ ]:
model = Sequential()
model.add(Dense(400, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))
model.add(Dense(400, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))

model.add(Dense(15**2, activation='linear'))

opt = Adam(lr = 0.001)
parameterList = {}
parameterList['model'] = model
parameterList['opt'] = opt

fir = FIR(CROSS, False, parameterList, 3000)

In [ ]:
fir.run()

Epoch:  100 / 3000 	Elapsed time:  0:01:33
Epoch:  200 / 3000 	Elapsed time:  0:03:04
Epoch:  300 / 3000 	Elapsed time:  0:04:29
Epoch:  400 / 3000 	Elapsed time:  0:05:50
Epoch:  500 / 3000 	Elapsed time:  0:07:08
Epoch:  600 / 3000 	Elapsed time:  0:08:23
Epoch:  700 / 3000 	Elapsed time:  0:09:32
Epoch:  800 / 3000 	Elapsed time:  0:10:36
Epoch:  900 / 3000 	Elapsed time:  0:11:38
Epoch:  1000 / 3000 	Elapsed time:  0:12:32
Epoch:  1100 / 3000 	Elapsed time:  0:13:24
Epoch:  1200 / 3000 	Elapsed time:  0:14:14
Epoch:  1300 / 3000 	Elapsed time:  0:15:00
Epoch:  1400 / 3000 	Elapsed time:  0:15:48
Epoch:  1500 / 3000 	Elapsed time:  0:16:46
Epoch:  1600 / 3000 	Elapsed time:  0:17:48
Epoch:  1700 / 3000 	Elapsed time:  0:18:41
Epoch:  1800 / 3000 	Elapsed time:  0:19:46
Epoch:  1900 / 3000 	Elapsed time:  0:20:37
Epoch:  2000 / 3000 	Elapsed time:  0:21:38


In [ ]:
fir.test()

In [ ]:
model = Sequential()
model.add(Dense(2000, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))
model.add(Dense(2000, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))

model.add(Dense(15**2, activation='linear'))

opt = Adam(lr = 0.001)
parameterList = {}
parameterList['model'] = model
parameterList['opt'] = opt

fir = FIR(CROSS, False, parameterList, 3000)

In [ ]:
fir.run()

In [ ]:
fir.test()

In [ ]:
fir = FIR(CROSS, False, parameterList, 2000)

In [ ]:
fir.run()

In [ ]:
fir.test()

In [ ]:
model = Sequential()
model.add(Dense(400, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))
model.add(Dense(400, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))

model.add(Dense(15**2, activation='linear'))

opt = SGD(lr=0.0005 , momentum=0.9, decay=1e-18, nesterov=False)

parameterList = {}
parameterList['model'] = model
parameterList['opt'] = opt

fir = FIR(CROSS, False, parameterList, 5000)

In [ ]:
fir.run()

In [ ]:
fir.test()

In [ ]:
model = Sequential()
model.add(Dense(2000, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))
model.add(Dense(2000, activation = 'relu', input_dim=15**2))
model.add(Dropout(0.3))

model.add(Dense(15**2, activation='linear'))

opt = SGD(lr=0.0005 , momentum=0.9, decay=1e-18, nesterov=False)

parameterList = {}
parameterList['model'] = model
parameterList['opt'] = opt

fir = FIR(CROSS, False, parameterList, 5000)

In [ ]:
fir.run()

In [ ]:
fir.test()

In [2]:
fir = FIR(CROSS, True, None, 500)

In [4]:
sys.stdout = open(os.devnull, 'w')
fir.run()

In [3]:
fir.test()

Action:  88 Row/Col  6 14
(15, 15)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0.0
[['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' 'X' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' 

In [10]:
sys.stdout = sys.__stdout__